version: '3.8'

services:
  # PostgreSQL database with pgvector extension (for local development)
  postgres:
    image: pgvector/pgvector:pg15
    container_name: remember-me-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: remember_me
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d remember_me"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - remember-me-dev

volumes:
  postgres_dev_data:
    driver: local

networks:
  remember-me-dev:
    driver: bridge