---
# Ansible Galaxy requirements
# Install with: ansible-galaxy install -r requirements.yml

collections:
  - name: community.postgresql
    version: ">=2.0.0"
  - name: community.general
    version: ">=5.0.0"

roles: []